spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003171

server:
  port: 80

logging:
  file: /usr/local/logs/apollo-configservice.log


